name: Generate badges
on:
  push:

jobs:
  badges:
    name: Generating badges
    runs-on: ubuntu-latest
    steps:
      - name: Generate PhpInsights badges
        uses: Lukasss93/phpinsights-badger@master
        with:
          url: 'https://www.lucapatera.it/phpinsights-badger.php'
          password: ${{ secrets.password }}
          path : './test.json'